#!/usr/bin/env bash
# tools/sync-settings.sh — deterministic deployment of ~/.claude/settings.json.
#
# Rendering model (ADR 0017):
#   deployed settings.json = deep-merge(template, machine overrides)
#   - template  : adapters/claude-code/user-level/settings.json.template (repo-managed)
#   - overrides : ~/.claude/settings.machine-overrides.json (machine-local, optional)
#   - merge     : jq `*` — objects merge recursively; arrays and scalars are
#                 replaced wholesale by the overrides side. Keep repo-managed
#                 policy (permissions.*, hooks.*) OUT of the overrides file.
#
# The deployed file is a build artifact: never hand-edit it. Repo-wide changes
# go to the template (and arrive via commit + git hook), machine-local values
# (notification prefs, model picker choices, ...) go to the overrides file.
#
# Usage:
#   tools/sync-settings.sh            # dry-run: show normalized diff
#   tools/sync-settings.sh --apply    # back up current file, then write
#   tools/sync-settings.sh --check    # quiet; exit 1 on drift, 0 if in sync
#   tools/sync-settings.sh --help

set -euo pipefail

# shellcheck source=./_lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"

cs_print_help() {
  cat <<'EOF'
sync-settings.sh — render ~/.claude/settings.json from the repo template plus
machine-local overrides (~/.claude/settings.machine-overrides.json).

Usage:
  tools/sync-settings.sh            Dry-run: show normalized diff
  tools/sync-settings.sh --apply    Back up current file, then write rendered JSON
  tools/sync-settings.sh --check    Quiet drift check (exit 1 on drift)
  tools/sync-settings.sh --help

Merge semantics: jq `*` deep-merge. Objects merge per key; arrays/scalars in
the overrides file replace the template value wholesale. Backups go to
~/.claude-system-backups/. Changes take effect from the next session.
EOF
}

cs_show_help_if_requested "${1:-}"

MODE="dry-run"
for arg in "$@"; do
  case "$arg" in
    --apply) MODE="apply" ;;
    --check) MODE="check" ;;
    --dry-run) MODE="dry-run" ;;
    *) cs_error "Unknown arg: $arg"; exit 2 ;;
  esac
done

cs_require_cmd jq
cs_require_root_dir

TEMPLATE="$CS_ROOT/adapters/claude-code/user-level/settings.json.template"
OVERRIDES="$HOME/.claude/settings.machine-overrides.json"
TARGET="$HOME/.claude/settings.json"
MANAGED_NOTE="generated by tools/sync-settings.sh (ADR 0017) — do not hand-edit. Repo policy: settings.json.template / machine-local values: settings.machine-overrides.json"

if [[ ! -f "$TEMPLATE" ]]; then
  cs_error "Template missing: $TEMPLATE"
  exit 1
fi
jq empty "$TEMPLATE" || { cs_error "Template is not valid JSON: $TEMPLATE"; exit 1; }

if [[ -f "$OVERRIDES" ]]; then
  jq empty "$OVERRIDES" || { cs_error "Overrides file is not valid JSON: $OVERRIDES"; exit 1; }
  overrides_src="$OVERRIDES"
else
  overrides_src=""
fi

render() {
  if [[ -n "$overrides_src" ]]; then
    jq -S -s --arg note "$MANAGED_NOTE" \
      '.[0] * (.[1] // {}) | .["// managed"] = $note' \
      "$TEMPLATE" "$overrides_src"
  else
    jq -S --arg note "$MANAGED_NOTE" \
      '. | .["// managed"] = $note' \
      "$TEMPLATE"
  fi
}

rendered="$(render)"

current=""
if [[ -f "$TARGET" ]]; then
  current="$(jq -S . "$TARGET" 2>/dev/null || true)"
fi

if [[ "$current" == "$rendered" ]]; then
  case "$MODE" in
    check) exit 0 ;;
    *) cs_success "In sync: $TARGET matches template + overrides." ;;
  esac
  exit 0
fi

case "$MODE" in
  check)
    exit 1
    ;;
  dry-run)
    cs_step "settings drift (normalized): deployed -> rendered"
    if [[ -z "$current" ]]; then
      cs_info "No deployed file (or invalid JSON) at $TARGET; full render would be written."
    fi
    diff -u -L "deployed:$TARGET" -L "rendered(template+overrides)" \
      <(printf '%s\n' "$current") <(printf '%s\n' "$rendered") || true
    cs_info "Apply with: tools/sync-settings.sh --apply"
    ;;
  apply)
    cs_acquire_lock sync-settings >/dev/null
    trap 'cs_release_lock sync-settings' EXIT
    mkdir -p "$HOME/.claude"
    if [[ -f "$TARGET" ]]; then
      cs_ensure_backup_dir
      bk="$(cs_backup_path_for "$TARGET")"
      cp "$TARGET" "$bk"
      cs_info "Backup: $bk"
    fi
    tmp="$(mktemp "$HOME/.claude/.settings.json.render.XXXXXX")"
    printf '%s\n' "$rendered" > "$tmp"
    jq empty "$tmp" || { cs_error "Rendered output is not valid JSON (bug)"; rm -f "$tmp"; exit 1; }
    mv "$tmp" "$TARGET"
    cs_success "Deployed: $TARGET (takes effect from the next session)"
    ;;
esac
